name: EasyJoin
main: me.espryth.easyjoin.Core
version: 2.1.2
api-version: 1.13
author: Espryth
depend: [PlaceholderAPI]
softdepend: [AuthMe]
commands:
  easyjoin:
    usage: /<command>
    aliases:
      - ej
